// Single source of truth for IPC channel names.
export const IPC = {
  // invoke: renderer -> main
  ProjectsAdd: 'projects:add',
  ProjectsList: 'projects:list',
  ProjectsCreateRepo: 'projects:createRepo',
  ProjectsListGithub: 'projects:listGithub',
  ProjectsCloneGithub: 'projects:cloneGithub',
  ProjectsAddRemote: 'projects:addRemote',
  SetupStatus: 'setup:status',
  WorkspacesCreate: 'workspaces:create',
  WorkspacesList: 'workspaces:list',
  WorkspacesArchive: 'workspaces:archive',
  SessionSend: 'session:send',
  GitStatus: 'git:status',
  GitCommitPush: 'git:commitPush',
  GitCreatePr: 'git:createPr',
  GitPull: 'git:pull',
  GitOpenGithub: 'git:openGithub',
  ShellOpenPath: 'shell:openPath',
  ProjectsRemove: 'projects:remove',
  PtyCreate: 'pty:create',
  PtyInput: 'pty:input',
  PtyResize: 'pty:resize',
  PtyKill: 'pty:kill',
  PtyRestart: 'pty:restart',
  OrchestratorSend: 'orchestrator:send',
  OrchestratorInterrupt: 'orchestrator:interrupt',
  OrchestratorHistory: 'orchestrator:history',
  SessionRemoteControl: 'session:remoteControl',
  ShareStart: 'share:start',
  ShareStop: 'share:stop',

  UiGetState: 'ui:getState',
  UiSaveState: 'ui:saveState',
  CodexStatus: 'codex:status',
  CodexSetup: 'codex:setup',
  MobileInfo: 'mobile:info',
  SessionUsage: 'session:usage',
  WorkspaceAuthGet: 'workspace:authGet',
  WorkspaceAuthSet: 'workspace:authSet',
  UsageSummary: 'usage:summary',
  ClipboardPaste: 'clipboard:paste',
  ClipboardCopy: 'clipboard:copy',
  ClipboardHistory: 'clipboard:history',
  ClipboardUse: 'clipboard:use',
  SessionPathFor: 'session:pathFor',
  SessionSetAgent: 'session:setAgent',
  ProjectsInitGit: 'projects:initGit',

  // guest mode (running on a host's credits) and the host's admin side
  GuestStatus: 'guest:status',
  GuestRedeem: 'guest:redeem',
  GuestLeave: 'guest:leave',
  GuestBalance: 'guest:balance',
  GuestUsage: 'guest:usage',
  GuestClipboardInvite: 'guest:clipboardInvite',
  GuestPendingInvite: 'guest:pendingInvite',
  ToolsStatus: 'tools:status',
  ToolsInstall: 'tools:install',
  RelayAdminStatus: 'relayAdmin:status',
  RelayAdminGuests: 'relayAdmin:guests',
  RelayAdminCreate: 'relayAdmin:create',
  RelayAdminInvite: 'relayAdmin:invite',
  RelayAdminTopUp: 'relayAdmin:topUp',
  RelayAdminAccess: 'relayAdmin:access',

  // updates, the Mac terminal paste path, support diagnostics
  UpdateStatus: 'update:status',
  UpdateInstall: 'update:install',
  ClipboardSaveBlob: 'clipboard:saveBlob',
  AppPaste: 'app:paste',
  AppDiagnostics: 'app:diagnostics',

  // events: main -> renderer
  EvSessionMessage: 'ev:session:message',
  EvSessionStatus: 'ev:session:status',
  EvActivity: 'ev:activity',
  EvFocusSession: 'ev:focusSession',
  EvPtyData: 'ev:pty:data',
  EvPtyExit: 'ev:pty:exit',
  EvGitStatus: 'ev:git:status',
  EvWorkspacesChanged: 'ev:workspaces:changed',
  EvShareStatus: 'ev:share:status',
  EvToolsProgress: 'ev:tools:progress',
  EvInviteLink: 'ev:inviteLink',
  EvUpdate: 'ev:update'
} as const
