// 35s @ 30fps. Eight scenes, hard-cut under a seam-split wipe — the app's own
// boot reveal used as the transition motif throughout.
import React from 'react'
import { AbsoluteFill, Audio, Easing, interpolate, Sequence, staticFile, useCurrentFrame } from 'remotion'
import { T } from './theme'
import {
  S1Hook,
  S2Fleet,
  S3Parallel,
  S4Mission,
  S5NeedsYou,
  S6Share,
  S7Phone,
  S8Outro
} from './scenes'

export const FPS = 30
export const DURATION = 1050

// scene boundaries (global frames)
const AT = {
  fleet: 90,
  parallel: 225,
  mission: 375,
  needsYou: 525,
  share: 630,
  phone: 750,
  outro: 885
}

// Two halves rush in, kiss at the centre (the cut happens under them), part.
const WIPE_LEN = 22
const SeamWipe: React.FC = () => {
  const frame = useCurrentFrame() // local 0..WIPE_LEN
  const meet = WIPE_LEN / 2
  const off =
    frame < meet
      ? interpolate(frame, [0, meet], [980, 0], { easing: Easing.in(Easing.cubic) })
      : interpolate(frame, [meet, WIPE_LEN], [0, 980], { easing: Easing.out(Easing.cubic) })
  const bloom = interpolate(frame, [meet - 3, meet, meet + 4], [0, 1, 0], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp'
  })
  const seamOpacity = interpolate(off, [0, 420], [1, 0], {
    extrapolateLeft: 'clamp',
    extrapolateRight: 'clamp'
  })
  return (
    <AbsoluteFill style={{ pointerEvents: 'none' }}>
      <div
        style={{
          position: 'absolute',
          inset: 0,
          right: '50%',
          background: T.surface0,
          transform: `translateX(${-off}px)`
        }}
      />
      <div
        style={{
          position: 'absolute',
          inset: 0,
          left: '50%',
          background: T.surface0,
          transform: `translateX(${off}px)`
        }}
      />
      <div
        style={{
          position: 'absolute',
          left: '50%',
          top: 0,
          bottom: 0,
          width: 2,
          marginLeft: -1,
          opacity: seamOpacity,
          background: `linear-gradient(to bottom, transparent, rgba(250,250,250,${0.45 + bloom * 0.55}), transparent)`,
          boxShadow: `0 0 ${14 + bloom * 46}px rgba(250,250,250,${0.2 + bloom * 0.5})`
        }}
      />
    </AbsoluteFill>
  )
}

export const Main: React.FC = () => {
  return (
    <AbsoluteFill style={{ background: T.surface0 }}>
      {/* Generated by scripts/make-music.mjs — 120 BPM, one impact per cut.
          To use your own track instead: replace public/audio.wav (or point
          this at an mp3) and re-render. */}
      <Audio src={staticFile('audio.wav')} volume={0.9} />
      <Sequence durationInFrames={AT.fleet}>
        <S1Hook />
      </Sequence>
      <Sequence from={AT.fleet} durationInFrames={AT.parallel - AT.fleet}>
        <S2Fleet />
      </Sequence>
      <Sequence from={AT.parallel} durationInFrames={AT.mission - AT.parallel}>
        <S3Parallel />
      </Sequence>
      <Sequence from={AT.mission} durationInFrames={AT.needsYou - AT.mission}>
        <S4Mission />
      </Sequence>
      <Sequence from={AT.needsYou} durationInFrames={AT.share - AT.needsYou}>
        <S5NeedsYou />
      </Sequence>
      <Sequence from={AT.share} durationInFrames={AT.phone - AT.share}>
        <S6Share />
      </Sequence>
      <Sequence from={AT.phone} durationInFrames={AT.outro - AT.phone}>
        <S7Phone />
      </Sequence>
      <Sequence from={AT.outro} durationInFrames={DURATION - AT.outro}>
        <S8Outro />
      </Sequence>

      {Object.values(AT).map((at) => (
        <Sequence key={at} from={at - WIPE_LEN / 2} durationInFrames={WIPE_LEN}>
          <SeamWipe />
        </Sequence>
      ))}
    </AbsoluteFill>
  )
}
